Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 153, in read_bytes
    bytes = self.rfile.read(num)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
ValueError: not enough values to unpack (expected 2, got 0)
Listening on port 1234 for clients..
----------------------------------------
Exception happened during processing of request from ('192.168.0.116', 52436)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.103', 54747)
----------------------------------------
Server terminated.
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 153, in read_bytes
    bytes = self.rfile.read(num)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 153, in read_bytes
    bytes = self.rfile.read(num)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 136, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 149, in handle
    self.read_next_message()
  File "/home/pi/.local/lib/python3.5/site-packages/websocket_server/websocket_server.py", line 161, in read_next_message
    b1, b2 = self.read_bytes(2)
ValueError: not enough values to unpack (expected 2, got 0)
Listening on port 1234 for clients..
----------------------------------------
Exception happened during processing of request from ('192.168.0.116', 52442)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.116', 52444)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('192.168.0.103', 54971)
----------------------------------------
Server terminated.
Listening on port 1234 for clients..
Server terminated.
